server:
  port: 8081


spring:
  datasource:
    url: jdbc:mysql://localhost:3306/microservicedb
    username: root
    password: 12345678
    driver-class-name: com.mysql.cj.jdbc.Driver




  jpa:
    hibernate:
      ddl-auto: update
      show-sql: true
      properties:
        hibernate:
          dialect: org.hibernate.dialect.MySQL8Dialect

  application:
    name: USER-SERVICE


  config:
    import: configserver:http://localhost:8085


management:
  health:
    circuitbreakers:
      enabled: true
  endpoints:
    web:
      exposure:
        include: health

  endpoint:
    health :
      show-details: "ALWAYS"
#management.endpoint.health.show-details: "ALWAYS"
#management.health.circuitbreakers.enabled: false
resilience4j:
  circuitbreakers:
    instance:
      ratingHotelBreaker:
        registerHealthIndicator: true
        eventConsumerBufferSize: 10
        failureRateThreshold: 50
        minimumNumberOfCalls: 5
        automaticTransitionFromOpenToHalfOpenEnabled: true
        waitDurationInOpenState: 6s
        permittedNumberOfCallsInHalfOpenState: 3
        slidingWindowSize: 10
        slidingWindowType: COUNT_BASED



#This is configuration can be used form configuration server which fetchs config form github above property
#eureka:
#  instance:
#    prefer-ip-address: true
#  client:
#    fetch-registry: true
#    register-with-eureka: true
#    service-url:
#      defaultZone: http://localhost:8761/eureka